// Generated by Selenium IDE
require('chromedriver');
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('useraddtocart', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('user add to cart', async function() {
    await driver.get("https://www.amazon.com.tr/")
    await driver.findElement(By.xpath("//input[@id=\'twotabsearchtextbox\']")).click()
    {
      const element = await driver.findElement(By.id("nav-link-accountList-nav-line-1"))
      await driver.actions({ bridge: true }).move(element).perform()
    }
    await driver.findElement(By.id("twotabsearchtextbox")).click()
    await driver.findElement(By.id("twotabsearchtextbox")).sendKeys("klavye")
    await driver.findElement(By.id("nav-search-submit-button")).click()
    await driver.findElement(By.xpath("//body/div[@id=\'a-page\']/div[@id=\'search\']/div[1]/div[1]/div[1]/span[3]/div[2]/div[11]/div[1]/div[1]/div[1]/div[1]/div[2]/span[1]/a[1]/div[1]")).click()
    await driver.findElement(By.xpath("//input[@id=\'add-to-cart-button\']")).click()
    await driver.findElement(By.xpath("//input[@id=\'twotabsearchtextbox\']")).click()
    await driver.findElement(By.id("twotabsearchtextbox")).click()
    await driver.findElement(By.id("twotabsearchtextbox")).sendKeys("bisiklet")
    await driver.findElement(By.id("nav-search-submit-button")).click()
    await driver.findElement(By.xpath("//body/div[@id=\'a-page\']/div[@id=\'search\']/div[1]/div[1]/div[1]/span[3]/div[2]/div[12]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]/a[1]/div[1]")).click()
    await driver.findElement(By.xpath("//input[@id=\'add-to-cart-button\']")).click()
    await driver.findElement(By.xpath("//header/div[@id=\'navbar\']/div[@id=\'nav-belt\']/div[3]/div[1]/a[4]/div[1]/span[2]")).click()
  })
})
